name: dart_rest_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  postgres: ^3.5.6
  http_parser: ^4.1.2
  mime: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
